# ~/.bashrc: executed by bash(1) for non-login shells.
export VISUAL=nvim
export EDITOR="$VISUAL"
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

mydir() {
    if  [ "$#" != 1 ] ; then
        echo "expection one argument"
    else
        mkdir $1
        cd $1
        touch CMakeLists.txt
        mkdir build;
    fi
}

brightness(){
    if [ "$#" != 1 ] ; then
        echo "expecting one argument - brightnes from 0 to 1"
    else
        xrandr --output HDMI-1 --brightness $1
        xrandr --output VGA-1 --brightness $1
    fi
}

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
# append to the history file, don't overwrite it
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
# Alias definitions.
if [ -f ~/dotfiles/bash/bash_aliases ]; then
    . ~/dotfiles/bash/bash_aliases
fi

set bell-style none

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

/usr/bin/setxkbmap -option "caps:swapescape"
source ~/catkin_ws/devel/setup.bash
source /opt/ros/melodic/setup.bash
#export PYTHONPATH=/usr/lib/python2.7/dist-packages/ranger
